# Generated by Django 3.2 on 2021-05-12 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-quantity_available']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='in_stock',
        ),
    ]
