# Generated by Django 3.2 on 2021-04-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210426_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(null=True, to='games.Genre'),
        ),
    ]
