# Generated by Django 3.2 on 2021-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210429_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='quantity_available',
            field=models.IntegerField(default=0, max_length=7858772994),
        ),
    ]
