# Generated by Django 3.2 on 2021-05-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210515_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='images/games/default.jpg', null=True, upload_to='images/games'),
        ),
    ]
