# Generated by Django 3.2 on 2021-05-08 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210508_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='quantity_available',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7858772994)]),
        ),
    ]
