# Generated by Django 3.2 on 2021-05-30 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='images/games/default.jpg', null=True, upload_to='images/games'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='quantity_available',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(7858772994)]),
        ),
    ]
