# Generated by Django 3.2 on 2021-04-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='games.Genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('', ''), ('Strategy', 'Strategy'), ('RPG', 'RPG'), ('Sports', 'Sports'), ('Races/Rally', 'Races/Rally'), ('Races/Arcade', 'Races/Arcade'), ('Races/Formula', 'Races/Formula'), ('Races/Off-Road', 'Races/Off-Road'), ('Action/FPS', 'Action/FPS'), ('Action/TPS', 'Action/TPS'), ('Action/Misc', 'Action/Misc'), ('Adventure', 'Adventure'), ('Puzzle/Skills', 'Puzzle/Skills'), ('Other', 'Other')], max_length=100, unique=True),
        ),
    ]
