# Generated by Django 3.2 on 2021-06-08 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_mpttcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
